"""The PR Review workflow.

Orchestrates a single review pass:

    1. Validate + guardrail the incoming request.
    2. Screen the (untrusted) PR description for prompt injection.
    3. Call gateway tools over MCP:
         - analyze_diff       (always)
         - check_test_coverage(always)
       => satisfies "the agent calls at least one tool".
    4. Aggregate findings -> risk band -> verdict (explainable).
    5. Redact secrets/PHI from everything that leaves the agent.
    6. Narrate a summary (deterministic by default, optional Claude).

Returns a single JSON-serialisable dict (the review).
"""

from __future__ import annotations

from typing import Any

from client.mcp_client import GatewayClient
from runtime import explain, guardrails, llm

SCHEMA_VERSION = "1.0"


def run_review(payload: dict[str, Any], *, prefer_mcp: bool = True) -> dict[str, Any]:
    report = guardrails.GuardrailReport()
    trace = explain.ReasoningTrace()

    # -- 1. Input validation --------------------------------------------------
    trace.add("validate_input", "Check request shape and size limits.")
    if not guardrails.validate_input(payload, report):
        trace.add("halt", f"Blocked by guardrails: {report.block_reason}")
        return _blocked_result(payload, report, trace)

    pr = payload["pull_request"]
    diff = pr.get("diff", "") or ""
    files = pr.get("files", []) or []

    # -- 2. Prompt-injection screening on untrusted text ----------------------
    trace.add("screen_injection",
              "Scan PR title/description for instruction-override attempts.")
    guardrails.screen_injection(pr.get("description", ""), report,
                                where="pr.description")
    guardrails.screen_injection(pr.get("title", ""), report, where="pr.title")

    # -- 3. Tool calls over the AgentCore Gateway (MCP) -----------------------
    gateway = GatewayClient(prefer_mcp=prefer_mcp)

    trace.add("tool:analyze_diff",
              "Call gateway analyze_diff on the unified diff.")
    diff_call = gateway.call("analyze_diff", {"diff": diff})

    trace.add("tool:check_test_coverage",
              "Call gateway check_test_coverage on the changed file list.")
    cov_call = gateway.call("check_test_coverage", {"files": files})

    used_real_tools = any(c.transport == "mcp-stdio" for c in gateway.calls)
    trace.add("tools_complete",
              f"{len(gateway.calls)} tool call(s) via "
              f"{gateway.calls[0].transport if gateway.calls else 'n/a'}.")

    analysis = diff_call.result or {"findings": [], "stats": {}}
    coverage = cov_call.result or {"gaps": [], "source_files": [], "test_files": []}
    findings = list(analysis.get("findings", []))
    coverage_gaps = coverage.get("gaps", [])

    # -- 4. Aggregate -> risk -> verdict --------------------------------------
    trace.add("aggregate",
              f"Combine {len(findings)} finding(s) and "
              f"{len(coverage_gaps)} coverage gap(s).")
    risk = explain.risk_level(findings, len(coverage_gaps))
    decision = explain.decide(findings, len(coverage_gaps))
    trace.add("decide", f"Verdict={decision['verdict']} "
                        f"(risk={risk['band']}): {decision['rationale']}")

    # -- 6. Narrate (uses pre-redaction evidence internally) ------------------
    narrator = llm.get_narrator()
    ctx = {
        "pull_request": {k: pr.get(k) for k in ("title", "author", "files")},
        "findings": findings,
        "coverage": coverage,
        "risk": risk,
        "decision": decision,
    }
    summary = narrator.summarize(ctx)
    trace.add("narrate", f"Summary generated by '{narrator.name}' narrator.")

    # -- 5. Output redaction (last line of defence) ---------------------------
    trace.add("redact_output",
              "Mask any secrets/PHI in findings and summary before emitting.")
    safe_findings = guardrails.redact_obj(findings, report, where="findings")
    safe_coverage = guardrails.redact_obj(coverage, report, where="coverage")
    safe_summary = guardrails.redact(summary, report, where="summary")

    confidence = explain.score_confidence(
        len(findings), used_real_tools, False, len(coverage_gaps))

    return {
        "schema_version": SCHEMA_VERSION,
        "pull_request": {
            "id": pr.get("id"),
            "title": pr.get("title"),
            "author": pr.get("author"),
            "files_changed": len(files),
        },
        "review": {
            "verdict": decision["verdict"],
            "risk": risk,
            "summary": safe_summary,
            "findings": safe_findings,
            "coverage": safe_coverage,
        },
        "explainability": {
            "reasoning_trace": trace.to_list(),
            "decision_rationale": decision["rationale"],
            "confidence": confidence,
            "tool_calls": [_call_view(c, report) for c in gateway.calls],
            "narrator": narrator.name,
        },
        "guardrails": report.to_dict(),
    }


def _call_view(call: Any, report: guardrails.GuardrailReport) -> dict[str, Any]:
    """Redacted, serialisable view of a recorded tool call."""
    return {
        "name": call.name,
        "transport": call.transport,
        "ok": call.ok,
        "error": call.error,
        "arguments": guardrails.redact_obj(
            _truncate(call.arguments), report, where=f"tool.{call.name}.args"),
        "result": guardrails.redact_obj(
            call.result, report, where=f"tool.{call.name}.result"),
    }


def _truncate(args: dict[str, Any], limit: int = 400) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for k, v in args.items():
        if isinstance(v, str) and len(v) > limit:
            out[k] = v[:limit] + f"... [+{len(v) - limit} chars]"
        else:
            out[k] = v
    return out


def _blocked_result(payload: dict[str, Any], report: guardrails.GuardrailReport,
                    trace: explain.ReasoningTrace) -> dict[str, Any]:
    pr = payload.get("pull_request", {}) if isinstance(payload, dict) else {}
    confidence = explain.score_confidence(0, False, True, 0)
    return {
        "schema_version": SCHEMA_VERSION,
        "pull_request": {"id": pr.get("id") if isinstance(pr, dict) else None},
        "review": {
            "verdict": "blocked",
            "risk": {"band": "unknown", "raw_score": 0.0},
            "summary": f"Request blocked by guardrails: {report.block_reason}",
            "findings": [],
            "coverage": {},
        },
        "explainability": {
            "reasoning_trace": trace.to_list(),
            "decision_rationale": report.block_reason,
            "confidence": confidence,
            "tool_calls": [],
            "narrator": "n/a",
        },
        "guardrails": report.to_dict(),
    }
